[workspace]
resolver = "3"
members = [
    "apps/desktop-core/storyarc-core",
    "apps/desktop-core/storyarc-ffi",
    "apps/desktop-linux",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.92"
repository = "https://github.com/me-cedric/StoryArc"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
