#!/usr/bin/env node
// build.mjs — one token source, two native outputs.
//
//   node scripts/build.mjs          write Swift + Kotlin into dist/
//   node scripts/build.mjs --check  contrast gate only, write nothing
//
// Generated files are gitignored. Each app copies them in during its build so
// neither platform can drift from the palette by hand-editing a colour.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { contrastRatio, oklchToSrgb } from './oklch.mjs'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const DIST = join(ROOT, 'dist')
const checkOnly = process.argv.includes('--check')

const read = (name) => JSON.parse(readFileSync(join(ROOT, 'tokens', name), 'utf8'))
const color = read('color.json')
const type = read('typography.json')
const layout = read('layout.json')

const isMeta = (key) => key.startsWith('$')
const entriesOf = (obj) => Object.entries(obj).filter(([key]) => !isMeta(key))

// ── Resolve every oklch() string to sRGB ─────────────────────────────────────

const resolved = {}
const gamutWarnings = []

for (const [group, tokens] of entriesOf(color)) {
  resolved[group] = {}
  for (const [name, token] of entriesOf(tokens)) {
    const fields = token.oklch ? { value: token.oklch } : { bg: token.bg, fg: token.fg }
    resolved[group][name] = {}
    for (const [field, raw] of Object.entries(fields)) {
      if (!raw) continue
      const srgb = oklchToSrgb(raw)
      if (srgb.outOfGamut) gamutWarnings.push(`${group}.${name}.${field} = ${raw}`)
      resolved[group][name][field] = srgb
    }
  }
}

// ── Contrast gate ────────────────────────────────────────────────────────────
//
// Text tokens that fail WCAG AA are a bug the design system should refuse to
// ship, not something a reviewer notices in a screenshot six weeks later.

const PAIRS = [
  ['dark.textPrimary',   'dark.surfaceCanvas',  4.5],
  ['dark.textPrimary',   'dark.surfaceRaised',  4.5],
  ['dark.textSecondary', 'dark.surfaceCanvas',  4.5],
  ['dark.textTertiary',  'dark.surfaceCanvas',  3.0],
  ['light.textPrimary',   'light.surfaceCanvas', 4.5],
  ['light.textPrimary',   'light.surfaceRaised', 4.5],
  ['light.textSecondary', 'light.surfaceCanvas', 4.5],
  ['light.textTertiary',  'light.surfaceCanvas', 3.0],
  ['brand.ember',       'dark.surfaceCanvas',  3.0],
  ['brand.emberStrong', 'light.surfaceCanvas', 3.0],
]

const rgbOf = (path) => {
  const [group, name] = path.split('.')
  return resolved[group][name].value.rgb
}

const failures = []
console.log('Contrast gate (WCAG 2.1):')
for (const [fg, bg, floor] of PAIRS) {
  const ratio = contrastRatio(rgbOf(fg), rgbOf(bg))
  const ok = ratio >= floor
  if (!ok) failures.push(`${fg} on ${bg}: ${ratio.toFixed(2)}:1 < ${floor}:1`)
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${ratio.toFixed(2).padStart(5)}:1  (min ${floor})  ${fg} on ${bg}`)
}

for (const [name, theme] of entriesOf(color.reader)) {
  const ratio = contrastRatio(resolved.reader[name].fg.rgb, resolved.reader[name].bg.rgb)
  const ok = ratio >= 7.0
  if (!ok) failures.push(`reader.${name}: ${ratio.toFixed(2)}:1 < 7:1`)
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${ratio.toFixed(2).padStart(5)}:1  (min 7.0)  reader.${name} (AAA — long-form body text)`)
  void theme
}

if (gamutWarnings.length) {
  console.warn(`\nOut of sRGB gamut, clipped: ${gamutWarnings.join(', ')}`)
}

if (failures.length) {
  console.error(`\n${failures.length} contrast failure(s):\n  ${failures.join('\n  ')}`)
  process.exit(1)
}

if (checkOnly) {
  console.log('\nCheck only — no files written.')
  process.exit(0)
}

// ── Emit ─────────────────────────────────────────────────────────────────────

const BANNER = (lang) => `${lang === 'swift' ? '//' : '//'} Generated by packages/design-tokens/scripts/build.mjs — do not edit.
${lang === 'swift' ? '//' : '//'} Edit packages/design-tokens/tokens/*.json and run \`pnpm tokens:build\`.
`

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1)
const swiftColor = (rgb) =>
  `Color(.sRGB, red: ${(rgb[0] / 255).toFixed(4)}, green: ${(rgb[1] / 255).toFixed(4)}, blue: ${(rgb[2] / 255).toFixed(4)}, opacity: 1)`
const kotlinColor = (rgb) =>
  `Color(0xFF${rgb.map((n) => n.toString(16).padStart(2, '0').toUpperCase()).join('')})`

// Swift
// `public import` because the tokens are part of DesignSystem's public API and the
// target builds with the InternalImportsByDefault upcoming feature enabled.
const swiftLines = [BANNER('swift'), 'public import SwiftUI', '', 'public enum StoryArcColor {']
for (const [group, tokens] of entriesOf(resolved)) {
  swiftLines.push(`    public enum ${pascal(group)} {`)
  for (const [name, fields] of Object.entries(tokens)) {
    for (const [field, srgb] of Object.entries(fields)) {
      const id = field === 'value' ? name : `${name}${pascal(field)}`
      const doc = (color[group][name].use || '').replace(/\n/g, ' ')
      if (doc) swiftLines.push(`        /// ${doc}`)
      swiftLines.push(`        public static let ${id} = ${swiftColor(srgb.rgb)}  // ${srgb.hex}`)
    }
  }
  swiftLines.push('    }')
}
swiftLines.push('}', '')

swiftLines.push('public enum StoryArcSpace {')
for (const [name, value] of entriesOf(layout.space)) {
  swiftLines.push(`    public static let ${name}: CGFloat = ${value}`)
}
swiftLines.push('}', '', 'public enum StoryArcRadius {')
for (const [name, value] of entriesOf(layout.radius)) {
  swiftLines.push(`    public static let ${name}: CGFloat = ${value}`)
}
swiftLines.push('}', '', 'public enum StoryArcDuration {')
for (const [name, value] of entriesOf(layout.motion.duration)) {
  swiftLines.push(`    public static let ${name}: Double = ${(value / 1000).toFixed(3)}`)
}
swiftLines.push('}', '', 'public enum StoryArcType {')
for (const [name, role] of entriesOf(type.scale)) {
  swiftLines.push(`    /// ${role.family} · ${role.weight} · ${role.size}/${role.lineHeight}`)
  swiftLines.push(`    public static let ${name}Size: CGFloat = ${role.size}`)
  swiftLines.push(`    public static let ${name}LineHeight: CGFloat = ${role.lineHeight}`)
  swiftLines.push(`    public static let ${name}Tracking: CGFloat = ${role.tracking}`)
}
swiftLines.push('}', '')

// Kotlin
const kotlinLines = [
  BANNER('kotlin'),
  'package app.storyarc.core.designsystem.tokens',
  '',
  'import androidx.compose.ui.graphics.Color',
  'import androidx.compose.ui.unit.dp',
  'import androidx.compose.ui.unit.sp',
  '',
  'object StoryArcColor {',
]
for (const [group, tokens] of entriesOf(resolved)) {
  kotlinLines.push(`    object ${pascal(group)} {`)
  for (const [name, fields] of Object.entries(tokens)) {
    for (const [field, srgb] of Object.entries(fields)) {
      const id = field === 'value' ? name : `${name}${pascal(field)}`
      const doc = (color[group][name].use || '').replace(/\n/g, ' ')
      if (doc) kotlinLines.push(`        /** ${doc} */`)
      kotlinLines.push(`        val ${id} = ${kotlinColor(srgb.rgb)}`)
    }
  }
  kotlinLines.push('    }')
}
kotlinLines.push('}', '', 'object StoryArcSpace {')
for (const [name, value] of entriesOf(layout.space)) kotlinLines.push(`    val ${name} = ${value}.dp`)
kotlinLines.push('}', '', 'object StoryArcRadius {')
for (const [name, value] of entriesOf(layout.radius)) kotlinLines.push(`    val ${name} = ${value}.dp`)
kotlinLines.push('}', '', 'object StoryArcDuration {')
for (const [name, value] of entriesOf(layout.motion.duration)) kotlinLines.push(`    const val ${name} = ${value}`)
kotlinLines.push('}', '', 'object StoryArcType {')
for (const [name, role] of entriesOf(type.scale)) {
  kotlinLines.push(`    /** ${role.family} · ${role.weight} · ${role.size}/${role.lineHeight} */`)
  kotlinLines.push(`    val ${name}Size = ${role.size}.sp`)
  kotlinLines.push(`    val ${name}LineHeight = ${role.lineHeight}.sp`)
}
kotlinLines.push('}', '')

mkdirSync(join(DIST, 'swift'), { recursive: true })
mkdirSync(join(DIST, 'kotlin'), { recursive: true })
writeFileSync(join(DIST, 'swift', 'StoryArcTokens.swift'), swiftLines.join('\n'))
writeFileSync(join(DIST, 'kotlin', 'StoryArcTokens.kt'), kotlinLines.join('\n'))
writeFileSync(join(DIST, 'tokens.resolved.json'), `${JSON.stringify({ color: resolved, typography: type, layout }, null, 2)}\n`)

console.log('\nWrote:')
console.log('  dist/swift/StoryArcTokens.swift')
console.log('  dist/kotlin/StoryArcTokens.kt')
console.log('  dist/tokens.resolved.json')
