<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <RepoRoot>$([MSBuild]::NormalizeDirectory('$(MSBuildThisFileDirectory)', '..', '..'))</RepoRoot>
  </PropertyGroup>

  <PropertyGroup>
    <CargoProfile Condition="'$(Configuration)' == 'Release'">release</CargoProfile>
    <CargoProfile Condition="'$(CargoProfile)' == ''">debug</CargoProfile>
  </PropertyGroup>
</Project>
