// Generated by packages/design-tokens/scripts/build.mjs — do not edit.
// Edit packages/design-tokens/tokens/*.json and run `pnpm tokens:build`.

package app.storyarc.core.designsystem.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object StoryArcColor {
    object Brand {
        /** Primary accent. Reading-lamp amber. Chrome-only — in-content accents defer to cover-derived colour. */
        val ember = Color(0xFFEC7C27)
        /** Pressed state, and the light-theme accent where 70% lightness would fail contrast on paper. */
        val emberStrong = Color(0xFFD2600C)
        /** Accent at rest on dark surfaces: progress rails, unselected indicators. */
        val emberMuted = Color(0xFF7C4521)
        /** Secondary. Indigo ink for links, informational chips, and the second series in charts. */
        val ink = Color(0xFF4A54A6)
    }
    object Dark {
        /** App background. */
        val surfaceCanvas = Color(0xFF0F0D0B)
        /** Cards, list rows, sheets. */
        val surfaceRaised = Color(0xFF1A1815)
        /** Menus, popovers, the fallback fill behind Liquid Glass when transparency is reduced. */
        val surfaceOverlay = Color(0xFF272320)
        /** Reader background. Deliberately not #000 — pure black smears on OLED during page turns and kills glass refraction. */
        val surfaceReader = Color(0xFF050403)
        /** Inset wells: search fields, empty states. */
        val surfaceSunken = Color(0xFF080706)
        /** Hairlines, separators. */
        val borderSubtle = Color(0xFF302D2A)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFF514C47)
        /** Titles and body. */
        val textPrimary = Color(0xFFF1EEEA)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFFAEAAA5)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF7D7A75)
        /** Modal scrim at 60% alpha; reader chrome gradient. */
        val scrim = Color(0xFF020201)
    }
    object Light {
        /** App background. Warm paper, not #FFF. */
        val surfaceCanvas = Color(0xFFF8F6F4)
        /** Cards, list rows, sheets. */
        val surfaceRaised = Color(0xFFFFFFFF)
        /** Menus, popovers, reduced-transparency fallback. */
        val surfaceOverlay = Color(0xFFFDFBFA)
        /** Reflowable-text reader background. Book stock cream. */
        val surfaceReader = Color(0xFFEDEBE7)
        /** Inset wells. */
        val surfaceSunken = Color(0xFFEFECE9)
        /** Hairlines, separators. */
        val borderSubtle = Color(0xFFE0DDDA)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFFBAB7B2)
        /** Titles and body. */
        val textPrimary = Color(0xFF181512)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFF59544F)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF847F7A)
        /** Modal scrim at 40% alpha. */
        val scrim = Color(0xFF302D2B)
    }
    object Status {
        /** Sync succeeded, source reachable. */
        val success = Color(0xFF4CB86A)
        /** Stale cache, partial download, degraded connection. */
        val warning = Color(0xFFEBAA2D)
        /** Auth failure, unreadable file, destructive action. */
        val danger = Color(0xFFE94646)
        /** Source disconnected. Neutral, never red — offline is normal, not an error. */
        val offline = Color(0xFF887E74)
        /** Available offline. The one badge allowed to compete with cover art. */
        val downloaded = Color(0xFF2DC08E)
    }
    object Reader {
        /** Default reflowable theme. */
        val themePaperBg = Color(0xFFEDEBE7)
        /** Default reflowable theme. */
        val themePaperFg = Color(0xFF1D1A17)
        /** Warm low-glare. */
        val themeSepiaBg = Color(0xFFE9DCC8)
        /** Warm low-glare. */
        val themeSepiaFg = Color(0xFF312620)
        /** Dark reflowable theme. Text is not pure white — reduces halation. */
        val themeNightBg = Color(0xFF0A0907)
        /** Dark reflowable theme. Text is not pure white — reduces halation. */
        val themeNightFg = Color(0xFFCDCAC6)
        /** Maximum-contrast accessibility theme. The only place pure black/white is allowed. */
        val themeContrastBg = Color(0xFF000000)
        /** Maximum-contrast accessibility theme. The only place pure black/white is allowed. */
        val themeContrastFg = Color(0xFFFFFFFF)
    }
}

object StoryArcSpace {
    val hair = 2.dp
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val lg = 16.dp
    val xl = 24.dp
    val xxl = 32.dp
    val xxxl = 48.dp
    val huge = 64.dp
    val gutter = 20.dp
    val section = 32.dp
    val coverGap = 14.dp
}

object StoryArcRadius {
    val none = 0.dp
    val cover = 4.dp
    val sm = 6.dp
    val md = 10.dp
    val lg = 16.dp
    val xl = 22.dp
    val sheet = 28.dp
    val capsule = 999.dp
}

object StoryArcDuration {
    const val instant = 100
    const val fast = 180
    const val normal = 260
    const val slow = 380
    const val pageTurn = 450
    const val chromeFade = 220
}

object StoryArcType {
    /** editorial · semibold · 34/41 */
    val displaySize = 34.sp
    val displayLineHeight = 41.sp
    /** ui · bold · 28/34 */
    val title1Size = 28.sp
    val title1LineHeight = 34.sp
    /** ui · bold · 22/28 */
    val title2Size = 22.sp
    val title2LineHeight = 28.sp
    /** ui · semibold · 20/25 */
    val title3Size = 20.sp
    val title3LineHeight = 25.sp
    /** ui · semibold · 17/22 */
    val headlineSize = 17.sp
    val headlineLineHeight = 22.sp
    /** ui · regular · 17/22 */
    val bodySize = 17.sp
    val bodyLineHeight = 22.sp
    /** ui · regular · 16/21 */
    val calloutSize = 16.sp
    val calloutLineHeight = 21.sp
    /** ui · regular · 15/20 */
    val subheadlineSize = 15.sp
    val subheadlineLineHeight = 20.sp
    /** ui · regular · 13/18 */
    val footnoteSize = 13.sp
    val footnoteLineHeight = 18.sp
    /** ui · regular · 12/16 */
    val captionSize = 12.sp
    val captionLineHeight = 16.sp
    /** ui · regular · 11/13 */
    val caption2Size = 11.sp
    val caption2LineHeight = 13.sp
}
