// Generated by packages/design-tokens/scripts/build.mjs — do not edit.
// Edit packages/design-tokens/tokens/*.json and run `pnpm tokens:build`.

package app.storyarc.core.designsystem.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object StoryArcColor {
    object Brand {
        /** Primary accent on dark surfaces. Reading-lamp amber. Chrome-only — in-content accents defer to cover-derived colour. */
        val ember = Color(0xFFEC7C27)
        /** Pressed state, and the light-theme accent where 70% lightness would fail contrast on paper. */
        val emberStrong = Color(0xFFD2600C)
        /** Accent at rest on dark surfaces: progress rails, unselected indicators. */
        val emberMuted = Color(0xFF7C4521)
        /** Secondary. Indigo ink for links, informational chips, and the second series in charts. */
        val ink = Color(0xFF4A54A6)
        /** The Natural theme's accent on its dark variant. Earthier than ember, so Natural is a theme rather than the same app in beige. */
        val clay = Color(0xFFC87C5E)
        /** The Natural theme's accent on its light variant, where clay at 66% lightness would fail on warm paper. */
        val clayStrong = Color(0xFF98492C)
    }
    object Dark {
        /** App background. */
        val surfaceCanvas = Color(0xFF0F0D0B)
        /** Cards, list rows, sheets. */
        val surfaceRaised = Color(0xFF1A1815)
        /** Menus, popovers, the fallback fill behind Liquid Glass when transparency is reduced. */
        val surfaceOverlay = Color(0xFF272320)
        /** Reader background. Deliberately not #000 — pure black smears on OLED during page turns and kills glass refraction. */
        val surfaceReader = Color(0xFF050403)
        /** Inset wells: search fields, empty states, cover letterboxing. */
        val surfaceSunken = Color(0xFF080706)
        /** Hairlines, separators. */
        val borderSubtle = Color(0xFF302D2A)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFF514C47)
        /** Titles and body. */
        val textPrimary = Color(0xFFF1EEEA)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFFAEAAA5)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF85817D)
        /** Modal scrim at 60% alpha; reader chrome gradient. */
        val scrim = Color(0xFF020201)
    }
    object Light {
        /** App background. Warm paper, not #FFF. */
        val surfaceCanvas = Color(0xFFF8F6F4)
        /** Cards, list rows, sheets. */
        val surfaceRaised = Color(0xFFFFFFFF)
        /** Menus, popovers, reduced-transparency fallback. */
        val surfaceOverlay = Color(0xFFFDFBFA)
        /** Reflowable-text reader background. Book stock cream. */
        val surfaceReader = Color(0xFFEDEBE7)
        /** Inset wells, cover letterboxing. */
        val surfaceSunken = Color(0xFFEFECE9)
        /** Hairlines, separators. */
        val borderSubtle = Color(0xFFE0DDDA)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFFBAB7B2)
        /** Titles and body. */
        val textPrimary = Color(0xFF181512)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFF59544F)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF6E6964)
        /** Modal scrim at 40% alpha. */
        val scrim = Color(0xFF302D2B)
    }
    object OledDark {
        /** App background. True black. */
        val surfaceCanvas = Color(0xFF000000)
        /** Cards, list rows, sheets — lifted off black so structure is still readable. */
        val surfaceRaised = Color(0xFF070504)
        /** Menus, popovers, reduced-transparency fallback. */
        val surfaceOverlay = Color(0xFF13110F)
        /** Reader background. Above true black on purpose — see $oledDarkNote. */
        val surfaceReader = Color(0xFF010101)
        /** Inset wells, cover letterboxing. */
        val surfaceSunken = Color(0xFF000000)
        /** Hairlines. Carries more weight here, since there is no surface tint to separate rows. */
        val borderSubtle = Color(0xFF1C1A18)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFF403C39)
        /** Titles and body. Not pure white — reduces halation against true black. */
        val textPrimary = Color(0xFFEAE7E4)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFFA7A4A1)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF7A7774)
        /** Modal scrim at 70% alpha. */
        val scrim = Color(0xFF000000)
    }
    object NaturalLight {
        /** App background. Warm cream stock. */
        val surfaceCanvas = Color(0xFFF4EEE3)
        /** Cards, list rows, sheets. */
        val surfaceRaised = Color(0xFFFAF6EF)
        /** Menus, popovers, reduced-transparency fallback. */
        val surfaceOverlay = Color(0xFFFDFAF4)
        /** Reader background. The one surface that carries the paper grain. */
        val surfaceReader = Color(0xFFEEE7D9)
        /** Inset wells, cover letterboxing. */
        val surfaceSunken = Color(0xFFE7E1D4)
        /** Hairlines, separators. */
        val borderSubtle = Color(0xFFD7D0C4)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFFA59E8F)
        /** Titles and body. Warm near-brown rather than neutral ink. */
        val textPrimary = Color(0xFF271D15)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFF605248)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF706257)
        /** Modal scrim at 40% alpha. */
        val scrim = Color(0xFF3A312A)
    }
    object NaturalDark {
        /** App background. Warm ink. */
        val surfaceCanvas = Color(0xFF16100C)
        /** Cards, list rows, sheets. */
        val surfaceRaised = Color(0xFF221B16)
        /** Menus, popovers, reduced-transparency fallback. */
        val surfaceOverlay = Color(0xFF2F2722)
        /** Reader background. The one surface that carries the paper grain. */
        val surfaceReader = Color(0xFF0D0805)
        /** Inset wells, cover letterboxing. */
        val surfaceSunken = Color(0xFF110C08)
        /** Hairlines, separators. */
        val borderSubtle = Color(0xFF39312B)
        /** Focus rings, selected outlines. */
        val borderStrong = Color(0xFF5A5049)
        /** Titles and body. Warm cream rather than neutral white. */
        val textPrimary = Color(0xFFEDE7DC)
        /** Metadata, subtitles. */
        val textSecondary = Color(0xFFB0AA9E)
        /** Timestamps, disabled, placeholder. */
        val textTertiary = Color(0xFF8A8479)
        /** Modal scrim at 60% alpha. */
        val scrim = Color(0xFF050302)
    }
    object Status {
        /** Sync succeeded, source reachable. */
        val success = Color(0xFF4CB86A)
        /** Stale cache, partial download, degraded connection. */
        val warning = Color(0xFFEBAA2D)
        /** Auth failure, unreadable file, destructive action. */
        val danger = Color(0xFFE94646)
        /** Source disconnected. Neutral, never red — offline is normal, not an error. */
        val offline = Color(0xFF887E74)
        /** Available offline. The one badge allowed to compete with cover art. */
        val downloaded = Color(0xFF2DC08E)
    }
    object ReadingThemes {
        /** Swatch only. Original leaves publisher styles on and overrides no colour. */
        val originalBg = Color(0xFFFCFCFA)
        /** Swatch only. Original leaves publisher styles on and overrides no colour. */
        val originalFg = Color(0xFF131110)
        /** Low-contrast dark. Soft off-white on deep neutral, tightened spacing. */
        val quietBg = Color(0xFF161310)
        /** Low-contrast dark. Soft off-white on deep neutral, tightened spacing. */
        val quietFg = Color(0xFFC7C3BF)
        /** Neutral light. Book-stock white, serif, comfortable default spacing. */
        val paperBg = Color(0xFFF5F1EC)
        /** Neutral light. Book-stock white, serif, comfortable default spacing. */
        val paperFg = Color(0xFF1D1A17)
        /** High contrast, heavier weight, wider spacing. Low vision without leaving the aesthetic. */
        val boldBg = Color(0xFFFCFCFC)
        /** High contrast, heavier weight, wider spacing. Low vision without leaving the aesthetic. */
        val boldFg = Color(0xFF060606)
        /** Warm dim. Cream on brown, generous line height. Long evening sessions. */
        val calmBg = Color(0xFF3F3329)
        /** Warm dim. Cream on brown, generous line height. Long evening sessions. */
        val calmFg = Color(0xFFE5D9C4)
        /** Narrow measure, high contrast, minimal decoration. Fewest words per line. */
        val focusBg = Color(0xFF040303)
        /** Narrow measure, high contrast, minimal decoration. Fewest words per line. */
        val focusFg = Color(0xFFE7E4E0)
    }
}

/** Reading-theme colours as hex, for renderers that parse their own. */
object StoryArcReadingThemeHex {
    const val originalBg = "#FCFCFA"
    const val originalFg = "#131110"
    const val quietBg = "#161310"
    const val quietFg = "#C7C3BF"
    const val paperBg = "#F5F1EC"
    const val paperFg = "#1D1A17"
    const val boldBg = "#FCFCFC"
    const val boldFg = "#060606"
    const val calmBg = "#3F3329"
    const val calmFg = "#E5D9C4"
    const val focusBg = "#040303"
    const val focusFg = "#E7E4E0"
}

object StoryArcSpace {
    val hair = 2.dp
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val lg = 16.dp
    val xl = 24.dp
    val xxl = 32.dp
    val xxxl = 48.dp
    val huge = 64.dp
    val gutter = 20.dp
    val section = 32.dp
    val coverGap = 14.dp
}

object StoryArcRadius {
    val none = 0.dp
    val cover = 4.dp
    val sm = 6.dp
    val md = 10.dp
    val lg = 16.dp
    val xl = 22.dp
    val sheet = 28.dp
    val capsule = 999.dp
}

object StoryArcDuration {
    const val instant = 100
    const val fast = 180
    const val normal = 260
    const val slow = 380
    const val pageTurn = 450
    const val chromeFade = 220
}

object StoryArcType {
    /** editorial · semibold · 34/41 */
    val displaySize = 34.sp
    val displayLineHeight = 41.sp
    /** ui · bold · 28/34 */
    val title1Size = 28.sp
    val title1LineHeight = 34.sp
    /** ui · bold · 22/28 */
    val title2Size = 22.sp
    val title2LineHeight = 28.sp
    /** ui · semibold · 20/25 */
    val title3Size = 20.sp
    val title3LineHeight = 25.sp
    /** ui · semibold · 17/22 */
    val headlineSize = 17.sp
    val headlineLineHeight = 22.sp
    /** ui · regular · 17/22 */
    val bodySize = 17.sp
    val bodyLineHeight = 22.sp
    /** ui · regular · 16/21 */
    val calloutSize = 16.sp
    val calloutLineHeight = 21.sp
    /** ui · regular · 15/20 */
    val subheadlineSize = 15.sp
    val subheadlineLineHeight = 20.sp
    /** ui · regular · 13/18 */
    val footnoteSize = 13.sp
    val footnoteLineHeight = 18.sp
    /** ui · regular · 12/16 */
    val captionSize = 12.sp
    val captionLineHeight = 16.sp
    /** ui · regular · 11/13 */
    val caption2Size = 11.sp
    val caption2LineHeight = 13.sp
}
